djangoProject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("", include("rath.urls", namespace="rath")),
    path("order/", include("order.urls", namespace="order")),
    path("admin/", admin.site.urls),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

order/urls.py
from django.urls import path
from . import views
app_name = "order"

urlpatterns = [
    path("my-order/", views.order_list, name="order-list"),
    path("order/add/", views.add_item, name="add"),
    path("cart/clear/", views.clear_cart, name="clear-cart"),
    path("order/create/", views.order_create, name="create"),
]

rath/urls.py
from django.urls import path
from . import views

app_name = "rath"

urlpatterns = [
    path('home/', views.home, name='home'),
    path('', views.index, name='index'),
    path('menu_button', views.menu_button, name="menu_button")
]

order/models.py
import uuid
from django.db import models
from django.contrib.sessions.models import Session
# from phonenumber_field.modelfields import PhoneNumberField
from rath.models import Item

def order_id_generator():
    return uuid.uuid4().hex[:11].upper()

class OrderItem(models.Model):
    session = models.ForeignKey(Session, on_delete=models.CASCADE)
    items = models.ManyToManyField(Item)
    quantity = models.IntegerField()

class Order(models.Model):
    order_number = models.CharField(max_length=11, unique=True, default=order_id_generator)
    created_date = models.DateTimeField(auto_now_add=True)
    order_items = models.ManyToManyField(OrderItem)
    name = models.CharField(max_length=255)
    email = models.EmailField(max_length=255)
    phone = models.CharField(max_length=20)
    address = models.TextField()
    data = models.JSONField()

    def __str__(self):
        return self.order_number

rath/models.py
from django.db import models


class Section(models.Model):
    name = models.CharField(max_length=200, help_text="Enter section name")
    slug = models.SlugField(
        max_length=200, unique=True, help_text="Slug title (unique identifier)"
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description = models.TextField(blank=True)
    items = models.ManyToManyField("Item")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Food Section"


class Category(models.Model):
    name = models.CharField(max_length=200)
    slug = models.SlugField(
        max_length=200, unique=True, help_text="Slug title (unique identifier)"
    )
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    description = models.TextField(blank=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ("-created",)
        verbose_name_plural = "Categories"


class DietType(models.Model):
    diet_name = models.CharField(max_length=255)
    diet_description = models.TextField()
    display_name_css_bg = models.CharField(max_length=20, default="green_bg")

    def __str__(self):
        return self.diet_name

    @property
    def get_display_title(self):
        return self.diet_name[0].upper

class Item(models.Model):
    category = models.ForeignKey(
        Category, on_delete=models.CASCADE, related_name="categories"
    )
    name = models.CharField(max_length=255, help_text="Food name")
    slug = models.SlugField(max_length=255, unique=True)
    diet = models.ForeignKey(DietType, on_delete=models.CASCADE, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    item_image = models.ImageField(upload_to="items/image", blank=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    def get_price(self):
        return "{:.2f}".format(self.price)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Item"
        verbose_name_plural = "Items"
        ordering = ("-created",)


class ItemAttribute(models.Model):
    item = models.ForeignKey(
        Item, on_delete=models.CASCADE, related_name="item_attributes"
    )
    name = models.CharField(max_length=100)
    diet = models.ForeignKey(DietType, blank=True, null=True, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    selected = models.BooleanField(default=False)

    def __str__(self):
        return self.name

order/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib import messages
from django.http import JsonResponse
from rath.models import Item, ItemAttribute
from .models import OrderItem
from .cart import Cart

# Create your views here.


def order_list(request):
    ordered_items = OrderItem.objects.all()
    return render(request, "order/order_items.html", {"ordered_items": ordered_items})


def add_item(request):
    if request.method == "POST":
        cart = Cart(request)
        if request.htmx:
            item_id = request.POST.get("item-id")
            quantity = request.POST.get("total")
            selected = request.POST.getlist("selected")
            item = Item.objects.get(id=item_id)
            if selected:
                extra = item.item_attributes.filter(id__in=selected).values()
                cart.add(product=item, quantity=int(quantity), extra=extra)
                return render(request, "rath/partials/success.html", {"item": item})
            else:
                cart = cart.add(product=item, quantity=int(quantity))
                return render(request, "rath/partials/success.html", {"item": item})
    else:
        return JsonResponse({"data": "Error"}, status=403)


def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    messages.add_message(request, messages.INFO, "Order cleared!")
    # messages.add_message(request, messages.INFO, 'Hello world.')
    return redirect("order:order-list")


def order_create(request):
    if request.method == "POST":

        if request.htmx:
            name = request.POST.get("name")
            phone = request.POST.get("phone")
            email = request.POST.get("email")
            address = request.POST.get("address")


    return JsonResponse({"created": "created"}, status=203)

rath/views.py
from django.shortcuts import render
from django.contrib.sessions.models import Session
from .models import Item, Category


def home(request):
    return render(request, "rath/home.html")


def index(request):
    categories = Category.objects.all()
    return render(request, "rath/index.html", {"categories": categories})


def menu_button(request):

    return render(
        request,
        "rath/menu.html",
    )

templates/base.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- EXTERNAL LINS START -->
    <script src="https://unpkg.com/htmx.org@1.6.1"></script>
    <link rel="stylesheet" href="{% static 'rath/css/style.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css"
        integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css" />
    <!-- EXTERNAL LINS END -->
    <title>{% block title %}SiteName{% endblock %}</title>
    <style>
        .mt-large{
            margin-top: 80px;
        }
    </style>
</head>

<body bgcolor=white>
    {% block navigation %}
    {% include "rath/partials/navigation.html" %}
    {% endblock %}

    {% if messages %}
    {% for message in messages %}
    <div class="mt-large alert {{ message.tags }} alert-dismissible fade show rounded-0" role="alert">
        {{message}}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
    {% endif %}

    {% block content %}
    {% endblock %}

    {% include 'rath/partials/footer.html' %}
    {% block scripts %}
    <!-- FOOTER SECTION END -->
    <!-- SCRIPT TAGS START -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js"></script>
    <script src="{% static 'rath/js/script.js' %}"></script>
    {% endblock %}
</body>

</html>

templates/checkout.html
{% extends 'base.html' %}

<h1> {{ "Checkout" }} </h1>

templates/home.html
{%  load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <!-- EXTERNAL LINS START -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous" />
    <script src=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" />
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/css/splide.min.css" />
    <!-- EXTERNAL LINS END -->
    <title>Home Page</title>
</head>

<body>
    <!-- ==== MODAL START ==== -->
    <!-- ==== Pizza Toppings ==== -->
    <!-- ==== MODAL END ==== -->

    <!-- ==== MODAL START ==== -->
    <!-- ==== Soda Toppings === -->
    <!-- ==== MODAL END ==== -->

    <!-- ==== MODAL START ==== -->
    <!-- ==== Burger Toppings ==== -->
    <!-- ==== MODAL END ==== -->


    <!-- ==== SIDEBAR START ==== -->

    <!-- ==== SIDEBAR END ==== -->

    <!-- HEADER START -->
    <div class="
				header_container
				position-fixed
				top-0
				lef-0
				py-2 py-md-3
				bg-white
				w-100
				shadow-sm
			">
        <div class="page_container">
            <div class="container-fluid position-relative">
                <div class="
							d-flex
							justify-content-center justify-content-md-between
							align-items-center
						">
                    <div class="logo_container">
                        <!-- <img src="images/logo.png" alt="logo" /> -->
                        <h1 class="fw-bold mb-0">Rathskeller</h1>
                    </div>
                    <div class="d-none d-md-flex">
                        <div>
                            <a class="text-decoration-none h6 text-dark mb-0" href="menu.html">Menu</a>
                        </div>
                        <div class="ms-3">
                            <a class="text-decoration-none h6 text-dark mb-0" href="cart.html">My Order</a>
                        </div>
                    </div>
                </div>

                <!-- HUMBERGAR START -->
                <div id="hambergerBtn" class="hamber_container d-block d-md-none position-absolute">
                    <i class="fas fa-bars"></i>
                </div>
                <!-- HUMBERGAR END -->
            </div>
        </div>
    </div>
    <!-- HEADER END -->

		<!-- HERO SECTION START -->
		<div class="hero_section position-relative">

			<!-- BOTTOM PRODUCT DETAILS START -->
			<div
				class="
					detailProduct_container
					position-absolute
					bottom-0
					w-100
					text-white
					py-2
					pe-4 pe-lg-0
					ps-4 ps-md-0
				"
			>
				<div class="page_container">
					<div class="container-fluid">
					<h1 class="mb-0">Rathskeller Pizza Grill</h1>
				</div>
				</div>
			</div>
			<!-- BOTTOM PRODUCT DETAILS END -->
		</div>
		<!-- HERO SECTION END -->

		<!-- BODY SECTION START -->
		<div class="body_section pb-4">
			<div class="page_container">
				<div class="container-fluid">
					<div class="row mt-4">
						<div class="col-12">
							<!-- SLIDER START -->
							<div class="mostpopular_container mt-4">
								<h4 class="fw-bold">Feature Products</h4>

								<div id="splide" class="splide">
									<div class="splide__track">
										<ul class="splide__list">
											<li data-bs-toggle="modal" data-bs-target="#exampleModal" class="splide__slide pointer px-2 py-2">
												<div class="popularCard boxCont">
													<img
														src="https://images.unsplash.com/photo-1555072956-7758afb20e8f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=687&q=80"
														alt=""
													/>
													<div class="p-3">
														<h6 class="mb-1 fw-bold">Margueirta</h6>
														<p class="small mb-0 text-secondary">
															Lorem ipsum dolor sit amet consectetur adipisicing
															elit. Dolore
														</p>
														<h6 class="fw-bold my-2">Starting from</h6>
														<h6 class="price h5 fw-bold mb-0">$ 10.00</h6>
													</div>
												</div>
											</li>
										</ul>
									</div>
								</div>
							</div>
							<!-- SLIDER START -->

							<div id="services" class="mt-5 pt-1">
                                <!-- UNDER LIST 1 START -->
								<a class="anchor" id="regular_flavors"></a>
                            <div class="mt-4">
                                <div class="d-flex justify-content-center align-items-center toggleHead">
                                    <h1 class="mb-0 fw500">Menu</h1>
                                </div>
                                <br/>
                                <br/>
                                <div class="container-fluid px-3">
                                    <h2 class="mb-0">Make Your Own Pizza<i class="fas fa-long-arrow-alt-right h4 mb-1"></i></h2>
                                    <div id="listData" class="row"></div>
                                </div>
                                <br/>
                                <br/>
                                <div class="container-fluid px-3">
                                    <h2 class="mb-0">Soft Drinks <i class="fas fa-long-arrow-alt-right h4 mb-1"></i></h2>
                                    <div id="listData2" class="row"></div>
                                </div>
                                <br/>
                                <br/>
                                <div class="container-fluid px-3">
                                    <h2 class="mb-0">Burger's <i class="fas fa-long-arrow-alt-right h4 mb-1"></i></h2>
                                    <div id="listData3" class="row"></div>
                                </div>
                            </div>
                            <!-- UNDER LIST 1 END -->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- BODY SECTION END -->

    <!-- FOOTER SECTION START -->
        <div class="footer_container mt-5">
        <div class="page_container">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12 col-sm-10 col-md-12 mx-auto">
                        <div class="row text-white">
                            <div class="col-6 col-md-3 d-flex flex-column">
                                <h4 class="text-uppercase">quick links</h4>
                                <a href="" class="small mb-2">About us</a>
                                <a href="" class="small mb-2">Add your restaurant</a>
                                <a href="" class="small mb-2">Deliver with us</a>
                            </div>
                            <div class="
										col-6 col-md-3
										contactUs
										d-flex
										flex-column
									">
                                <h4 class="text-uppercase">Contacs</h4>
                                <a href=""><i class="bi bi-geo-alt-fill me-2 color2"></i>
										<span class="small"
											>Lorem ipsum dolor sit amet consectetur adipisicing elit.</span
										>
									</a>
                                <a href=""><i class="bi bi-telephone-fill me-2 color2"></i>
										<span class="small"> 1323554545 </span>
									</a>
                                <a href=""><i class="bi bi-envelope-fill me-2 color2"></i
										><span class="small">info@.com </span>
									</a>
                            </div>
                            <div class="col-12 col-md-2 ms-auto d-flex flex-column mt-5 mt-md-0">
                                <h4 class="text-uppercase">follow us</h4>
                                <div class="followUsIcon d-flex align-items-center">
                                    <div><i class="bi bi-facebook"></i></div>
                                    <div><i class="bi bi-twitter ms-2"></i></div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- FOOTER SECTION END -->

    <!-- SCRIPT TAGS START -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@splidejs/splide@latest/dist/js/splide.min.js"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/rath/index.html
{% extends "base.html" %}

{% block content %}
{% include "rath/partials/hero.html" %}
<div class="container my-5">
    <div class="d-flex justify-content-center align-items-center toggleHead">
        <h1 class="mb-0 fw500 my-5">Product List</h1>
    </div>
    {% for category in categories %}

    <h2 class="mb-0">{{category.name}} <i class="fas fa-long-arrow-alt-right h4 mb-1"></i></h2>

    <div id="listData" class="row my-5">
        {% for item in category.categories.all %}
        <div class="modal fade" id="item-{{item.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
            aria-hidden="true">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title" id="exampleModalLabel">{{item.name}}</h5>
                        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                    </div>
                    <div class="modal-body mb-0">

                        <div id="notify-{{item.id}}"></div>
                        <p class="my-2">
                            {{item.description}}
                        </p>
                        <p class="fw-bold mb-0">Price: $<span id=price-header-{{item.id}}>{{item.price}}<span></p>
                    </div>
                    <form action="{% url 'order:add' %}" method="post" hx-post="{% url 'order:add' %}"
                        hx-target="#notify-{{item.id}}">
                        <input type="hidden" name="item-id" value={{item.id}}>
                        {% csrf_token %}
                        <div>
                            {# <h6 class="bg-light py-2 fw-bold px-4">8<sup>th</sup> PIZZA TOPPING</h6> #}
                            {% for extra in item.item_attributes.all %}
                            <div
                                class="px-4 d-flex justify-content-between align-items-center py-2 border-bottom border-1">
                                <div class="d-flex align-items-center">
                                    <label class="form-check-label">
                                        <!-- <span class="checkbox-custom rectangular"></span> -->
                                        <input class="form-check-input select-extra" data-extra="{{extra.price}}"
                                            type="checkbox" name="selected" data-extra-id="{{extra.id}}"
                                            value="{{extra.id}}">
                                    </label>

                                    <p class="mb-0 fw600 ps-1 pe-3">
                                        {{extra.name}}
                                    </p>
                                    <span>
                                        <small class="f10 bg-gray_ px-2 fw-bold py-1 rounded-pill">
                                            +$<span class="extra">{{extra.price}}</span>
                                        </small>
                                    </span>
                                </div>
                                <p class="mb-0 rounded-circle {{extra.diet.display_name_css_bg}} px-1 text-dark">
                                    {{extra.diet.get_display_title}}</p>
                            </div>
                            {% endfor %}

                            <!-- AMOUNT START -->
                            <div class="my-4">
                                <h4 class="text-center">Total: $<span id="total-{{item.id}}"
                                        data-total={{item.price}}>{{item.price}}</span></h4>
                                <div class="d-flex justify-content-center align-items-center topping_btns mt-3">
                                    <button type="button"
                                        class="btn1 d-flex align-items-center justify-content-between w-100">
                                        <p class="mb-0 w-100 h2 minus" data-price={{item.price}} data-id={{item.id}}>-
                                        </p><input type="text" name="total" value="1"
                                            class="bg-transparent text-center border-0 h5 mb-0">
                                        <p class="h2 w-100 mb-0 add" data-price={{item.price}} data-id={{item.id}}>+</p>
                                        </buton>
                                        <button class="btn2 ms-3" type="submit">Add to My Order</button>
                                </div>
                            </div>
                            <!-- AMOUNT END -->
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-12 col-lg-6 mt-4">

            <div data-bs-toggle="modal" data-bs-target="#item-{{item.id}}"
                class="d-flex align-items-center listCardCont boxCont pointer">
                <div>
                    {% if item.item_image %}
                    <img src="{{ item.item_image.url }}" alt="">
                    {% endif %}
                </div>
                <div class="ms-4 py-2">
                    <h6 class="mb-1 mb-0 h5">{{item.name}}</h6>
                    <p class="small mb-0 text-secondary mt-1 px-2">
                        {{item.description|capfirst|truncatewords:10}}
                    </p>
                    <div class="d-flex align-items-baseline mt-1">
                        <h6 class="price h4 mb-0 fw-bold"><i class="bi bi-cart3"></i> ${{item.get_price}}</h6>
                    </div>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}
</div>
{% endblock %}

{% block scripts %}
<script>
    const addBtn = document.querySelectorAll(".add");
    const minusBtn = document.querySelectorAll(".minus");
    const extraCheck = document.querySelectorAll(".select-extra");


    addBtn.forEach(btn => {
        const limit = 10
        btn.addEventListener("click", function (e) {
            const inputElement = e.target.previousElementSibling;
            if (inputElement.value < limit)
                inputElement.value++
            TotalId = 'total-' + e.target.dataset.id
            const total = document.getElementById(TotalId);
            total.innerHTML = parseInt(e.target.dataset.price) * inputElement.value
            priceHeader = "price-header-" + e.target.dataset.id
            document.getElementById(priceHeader).innerHTML = parseInt(e.target.dataset.price) *
                inputElement.value
        })
    })

    minusBtn.forEach(btn => {
        btn.addEventListener("click", function (e) {
            const inputElement = e.target.nextElementSibling;
            if (inputElement.value <= 1) {
                console.log("negative values")
            } else {
                inputElement.value--
                TotalId = 'total-' + e.target.dataset.id
                const total = document.getElementById(TotalId);

                total.innerHTML = parseInt(e.target.dataset.price) * inputElement.value
                priceHeader = "price-header-" + e.target.dataset.id
                document.getElementById(priceHeader).innerHTML = parseInt(e.target.dataset.price) *
                    inputElement.value

            }
        })
    })
    extraCheck.forEach(check => {
        check.addEventListener("change", function (e) {
            if (e.target.checked == true) {
                // console.log(e.target.value)
                const i = 'total-' + e.target.dataset.extraId
                const addTotal = document.getElementById(i)
                const extraPrice = parseInt(e.target.dataset.extra)
                total = parseInt(addTotal.dataset.total)
                console.log(addTotal)
                // extra = extraPrice + total;
                // addTotal.innerHTML = extra
            }
        })
    })
</script>
{% endblock %}

templates/rath/partials/hero.html
<div class="hero_section position-relative">

    <!-- BOTTOM PRODUCT DETAILS START -->
    <div class="
            detailProduct_container
            position-absolute
            bottom-0
            w-100
            text-white
            py-2
            pe-4 pe-lg-0
            ps-4 ps-md-0
        ">
        <div class="page_container">
            <div class="container-fluid">
            <h1 class="mb-0">Rathskeller Pizza Grill</h1>
        </div>
        </div>
    </div>
    <!-- BOTTOM PRODUCT DETAILS END -->
</div>

templates/rath/partials/navigation.html
{% load i18n %}
{% load static %}
<div class="
				header_container
				position-fixed
				top-0
				lef-0
				py-2 py-md-3
				bg-white
				w-100
				shadow-sm
			">
        <div class="page_container">
            <div class="container-fluid position-relative">
                <div class="
							d-flex
							justify-content-center justify-content-md-between
							align-items-center
						">
                    <div class="logo_container">
                        <!-- <img src="assets/images/logo.png" alt="logo" /> -->
                        <h1 class="fw-bold mb-0">Rathskeller</h1>
                    </div>
                    <div class="d-none d-md-flex">
                        <div>
                            <a class="text-decoration-none h6 text-dark mb-0" href="{% url 'rath:index' %}">Menu</a>
							</div>
							<div class="ms-3">
								<a class="text-decoration-none h6 text-dark mb-0" href="{% url 'order:order-list' %}">My Order</a>
							</div>
						</div>
					</div>

					<!-- HUMBERGAR START -->
					<div id="hambergerBtn" class="hamber_container d-block d-md-none position-absolute">
						<i class="fas fa-bars"></i>
					</div>
					<!-- HUMBERGAR END -->
				</div>
			</div>
		</div>

templates/rath/partials/success.html
<div class="alert alert-success alert-dismissible fade show" role="alert">
  <strong>Hey!</strong> <span class="fs-4 badge">{{item.name}}</span> was succefully added to your orders!.
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>